[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# Solidity version supporting transient storage (required for Uni V4)
solc = "0.8.26"
evm_version = "cancun"

# Optimizer settings
optimizer = true
optimizer_runs = 1000000
via_ir = true

# Gas reporting
gas_reports = ["*"]

# Fuzz testing configuration
[fuzz]
runs = 1000
max_test_rejects = 65536
seed = '0x3e8'
dictionary_weight = 40
include_storage = true
include_push_bytes = true

# Invariant testing configuration
[invariant]
runs = 256
depth = 15
fail_on_revert = false
call_override = false
dictionary_weight = 80
include_storage = true
include_push_bytes = true

# Via IR for better optimization (needed for complex contracts)
via_ir = true

# Allow FFI for advanced testing
ffi = true

# Formatter configuration
[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true
int_types = "long"
# Exclude patterns from formatting
ignore = [
    "lib/**",
    "out/**", 
    "cache/**",
    "broadcast/**",
    "node_modules/**"
]

# RPC endpoints (for mainnet forking if needed)
[rpc_endpoints]
mainnet = "https://eth-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
sepolia = "https://eth-sepolia.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
